export type SourceType = "official" | "campus_org" | "student";
export type StudentLevel = "undergraduate" | "graduate" | "both";

export type ContentItem = {
  id: string;
  category: string;
  title: string;
  summary: string;
  body: string;
  audience: string;
  studentLevel: StudentLevel;
  campus?: string | null;
  college?: string | null;
  sourceType: SourceType;
  sourceName: string;
  sourceUrl?: string | null;
  sourcePublishedAt?: string | null;
  checkedAt?: string | null;
  deadlineAt?: string | null;
  validity?: "active" | "expired" | "possibly_invalid";
};

export const categories = [
  { slug: "course", label: "选课与课程", mark: "课", description: "培养方案、选课通知与真实课程体验" },
  { slug: "club", label: "社团", mark: "社", description: "校级社团入口、招新与活动" },
  { slug: "student-union", label: "学生会", mark: "会", description: "校院学生组织与权益服务" },
  { slug: "activity", label: "校园活动", mark: "活", description: "讲座、志愿服务与文体活动" },
  { slug: "competition", label: "竞赛报名", mark: "赛", description: "报名通知、资格与截止日期" },
  { slug: "tutoring", label: "竞赛辅导", mark: "辅", description: "备赛经验、组队与训练资源" },
  { slug: "postgraduate", label: "保研", mark: "保", description: "推免政策、夏令营与经验" },
  { slug: "abroad", label: "留学", mark: "留", description: "交换、公派与国际合作项目" },
  { slug: "exam", label: "考研", mark: "研", description: "研招政策、宣讲与备考信息" },
] as const;

export const sourceLabels: Record<SourceType, string> = {
  official: "官方渠道",
  campus_org: "校内组织",
  student: "学生经验",
};

export const seedItems: ContentItem[] = [
  {
    id: "graduate-registration-2026",
    studentLevel: "graduate",
    category: "exam",
    title: "2026年秋季学期研究生注册安排",
    summary: "研究生院已公布线上注册时间与培养单位审核流程，请按通知要求及时完成。",
    body: "本条为校方通知索引。具体注册对象、时间、审核步骤及特殊情况办理方式，请以研究生院原文为准。",
    audience: "全体研究生",
    campus: "全校",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/",
    sourcePublishedAt: "2026-07-23",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-08-30T22:00:00+08:00",
  },
  {
    id: "graduate-open-day-2026",
    studentLevel: "graduate",
    category: "postgraduate",
    title: "第十二届研招校园开放日活动安排",
    summary: "研究生院汇总各招生单位开放日方案与报名入口，适合关注推免和研究生培养的同学查阅。",
    body: "活动报名已结束，页面保留为后续准备参考。各学院具体安排、申请材料和录取政策以原通知为准。",
    audience: "有推免或考研意向的学生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/",
    sourcePublishedAt: "2026-06-23",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-06-30T17:00:00+08:00",
    validity: "expired",
  },
  {
    id: "graduate-design-competition-2026",
    studentLevel: "graduate",
    category: "competition",
    title: "研究生“美丽中国”创新设计大赛校内选拔",
    summary: "研究生院发布校内选拔通知，正文包含赛道说明、参赛要求与校赛安排。",
    body: "请通过原文确认最新报名节点、作品规范和承办单位联系方式。本平台不代替官方报名系统。",
    audience: "在校研究生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/info/1105/18075.htm",
    sourcePublishedAt: "2026-07-06",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-08-07T23:59:00+08:00",
  },
  {
    id: "undergraduate-course-policy",
    studentLevel: "undergraduate",
    category: "course",
    title: "本科课程修读与选课官方入口",
    summary: "集中查看选课通知、课程修读管理、专业目录、通选课专题网与教务办事指南。",
    body: "选课轮次、容量调整、退补选和学分认定可能随学期变化。请优先查看教务处最新通知，并在学校信息门户完成实际操作。",
    audience: "本科生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）教务处",
    sourceUrl: "https://jwc.cug.edu.cn/",
    checkedAt: "2026-08-07",
  },
  {
    id: "cug-club-federation",
    studentLevel: "both",
    category: "club",
    title: "大学生社团联合会与社团事务入口",
    summary: "校团委公开的社团管理与服务组织入口，可查询社团工作和相关通知。",
    body: "社团招新与活动信息可能由各社团另行发布。加入前建议核对主办方、地点、费用与校内审批情况。",
    audience: "全体学生",
    sourceType: "campus_org",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/txzz/dxsstlhh.htm",
    checkedAt: "2026-08-07",
  },
  {
    id: "cug-student-union",
    studentLevel: "both",
    category: "student-union",
    title: "校学生会组织与服务信息",
    summary: "查看校学生会组织体系、权益服务、成长服务与校园活动相关信息。",
    body: "校学生会在校团委指导下开展学生服务。各学院学生会信息请继续通过对应学院官方渠道核验。",
    audience: "全体学生",
    sourceType: "campus_org",
    sourceName: "中国地质大学（武汉）学生会",
    sourceUrl: "https://youth.cug.edu.cn/txzz/xxsh.htm",
    checkedAt: "2026-08-07",
  },
  {
    id: "cug-youth-activities",
    studentLevel: "both",
    category: "activity",
    title: "校团委校园活动与实践通知",
    summary: "汇总社会实践、志愿服务、校园文化与学生组织活动的官方公告入口。",
    body: "活动时间与报名对象以每篇通知为准。对来源不明的群聊、收费和代报名信息保持谨慎。",
    audience: "全体学生",
    sourceType: "official",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/",
    checkedAt: "2026-08-07",
  },
  {
    id: "cug-international-cooperation",
    studentLevel: "both",
    category: "abroad",
    title: "校际交流与国际合作官方入口",
    summary: "查看国际合作处发布的校际交流、国际项目与涉外事务通知。",
    body: "留学项目涉及学分、费用、签证和培养方案时，请同时向所在学院与国际合作处确认，不以学生经验替代正式政策。",
    audience: "有交换或留学意向的学生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）国际合作处",
    sourceUrl: "https://gjhzc.cug.edu.cn/",
    checkedAt: "2026-08-07",
  },
  {
    id: "undergraduate-international-projects-2026",
    studentLevel: "undergraduate",
    category: "abroad",
    title: "2026年度学院自建本科生国际交流项目",
    summary: "国际合作处面向学院组织申报本科生短期课程、实习实践等国际交流项目，项目实施期为2026年4月至2027年4月。",
    body: "该轮学院申报已截止，保留为本科生了解学校国际交流项目建设和经费支持范围的官方参考。后续学生报名应以所在学院和国际合作处的新通知为准。",
    audience: "本科生及各学院项目负责人",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）国际合作处",
    sourceUrl: "https://gjhzc.cug.edu.cn/info/1013/15565.htm",
    sourcePublishedAt: "2026-04-23",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-05-08T17:00:00+08:00",
    validity: "expired",
  },
  {
    id: "student-innovation-projects-2026",
    studentLevel: "both",
    category: "tutoring",
    title: "2026年大学生自主创新资助计划立项名单",
    summary: "校团委公示创新训练类及实践类团队立项结果，可用于了解学校支持的项目方向和后续报账、中期考核入口。",
    body: "本条是已结束的立项公示，不是新的报名通知。名单以原文附件为准；后续报账和结题要求需继续查看校团委最新通知。",
    audience: "本科生、研究生创新实践团队",
    sourceType: "official",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/info/1123/13709.htm",
    sourcePublishedAt: "2026-07-06",
    checkedAt: "2026-08-07",
    validity: "expired",
  },
  {
    id: "top-student-clubs-2026",
    studentLevel: "both",
    category: "club",
    title: "2026年“十大标兵社团”名单",
    summary: "校团委公布本年度十个标兵社团，覆盖公益助学、海洋科普、曲艺、民族文化、龙狮、校史研习等方向。",
    body: "名单包括山中花儿爱心助学团、蓝点海洋协会、中乐相声社、夏心续梦公益社团、启明星盲校支教团、石榴籽民族文化社、大学生龙狮团、大学生“红色之声”宣讲社团、研究生心理协会和南望兰台校史研习社。是否招新及加入方式请以社团后续官方通知为准。",
    audience: "希望了解或加入学生社团的学生",
    sourceType: "official",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/info/1123/12099.htm",
    sourcePublishedAt: "2026-04-18",
    checkedAt: "2026-08-07",
  },
  {
    id: "volunteer-service-teams-2026",
    studentLevel: "both",
    category: "activity",
    title: "2026年志愿服务优秀团队参考名单",
    summary: "校团委公布十佳大学生志愿服务团队，可作为查找学院志愿者协会和公益实践组织的官方索引。",
    body: "公示覆盖地球与行星科学学院、资源学院、材料与化学学院、环境学院、人工智能与自动化学院、经济管理学院、地理与信息工程学院等志愿服务团队。该公示已结束，参与活动请查看各组织最新通知。",
    audience: "有志愿服务意向的学生",
    sourceType: "official",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/info/1123/11889.htm",
    sourcePublishedAt: "2026-04-12",
    checkedAt: "2026-08-07",
    validity: "expired",
  },
  {
    id: "summer-social-practice-2026",
    studentLevel: "both",
    category: "activity",
    title: "2026年暑期“三下乡”社会实践专题",
    summary: "校团委发布暑期社会实践总体安排，涵盖基层实践、长江大保护专项和海外社会实践等方向。",
    body: "通知面向2026年12月前仍在校的大学生，鼓励党团支部、班级、学生组织、社团和研究生导学团队跨学科组队。不同专项的时间和材料要求不同，请进入原文逐项核对。",
    audience: "符合通知条件的在校本科生、研究生",
    sourceType: "official",
    sourceName: "共青团中国地质大学（武汉）委员会",
    sourceUrl: "https://youth.cug.edu.cn/info/1123/13499.htm",
    sourcePublishedAt: "2026-06-25",
    checkedAt: "2026-08-07",
  },
  {
    id: "graduate-math-modeling-2026",
    studentLevel: "graduate",
    category: "competition",
    title: "第二十三届中国研究生数学建模竞赛校内报名",
    summary: "面向在校硕博研究生及2026级研究生，专业不限；学校安排赛前资料、选拔和培训。报名截至9月10日。",
    body: "竞赛将于2026年9月23日至27日举行。参赛者应具备数学建模、编程、专业分析或论文写作能力；除2026级研究生外，其他年级不允许跨校、跨单位组队。报名方式和校内培训安排以原文为准。",
    audience: "在校硕博研究生、2026级研究生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/info/1105/17415.htm",
    sourcePublishedAt: "2026-06-04",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-09-10T23:59:00+08:00",
  },
  {
    id: "graduate-ai-competition-2026",
    studentLevel: "graduate",
    category: "competition",
    title: "“华为杯”研究生人工智能创新大赛校内选拔",
    summary: "开放命题、地方赛题和企业赛题均可报名，在校研究生或已确认录取的准研究生可参加，报名截至8月25日。",
    body: "可个人参赛或最多4人组队，在读研究生比例需不低于50%，队长须为在读研究生；作品材料截至9月1日提交。请从原文进入大赛官网并核对校内安排。",
    audience: "在校研究生、已确认录取的准研究生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/info/1105/17585.htm",
    sourcePublishedAt: "2026-06-16",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-08-25T23:59:00+08:00",
  },
  {
    id: "graduate-double-carbon-2026",
    studentLevel: "graduate",
    category: "competition",
    title: "第五届中国研究生“双碳”创新与创意大赛校赛",
    summary: "设置清洁能源、储能与氢能、自然碳汇、绿色制造、循环经济和数字智能赋能碳中和等赛道，作品截至8月10日提交。",
    body: "参赛对象包括在读研究生（含非全日制）及已获本校研究生录取资格的本科生。每队3至6人；含本科生或非全日制研究生时，须由全日制研究生担任队长，并满足原文的人员比例要求。",
    audience: "在读研究生、已获本校研究生录取资格的本科生",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/info/1105/18035.htm",
    sourcePublishedAt: "2026-07-02",
    checkedAt: "2026-08-07",
    deadlineAt: "2026-08-10T23:59:00+08:00",
  },
  {
    id: "graduate-electronic-design-2026",
    studentLevel: "graduate",
    category: "competition",
    title: "第二十一届中国研究生电子设计竞赛校内选拔",
    summary: "赛事包含技术竞赛和商业计划书专项赛，覆盖嵌入式、智能制造、通信、人工智能和交叉学科等方向。",
    body: "该轮校内选拔已结束，页面保留为下一届备赛参考。参赛对象为全日制在校研究生及取得入学资格的2026级研究生新生，具体赛道与材料规范以原文为准。",
    audience: "研究生电子设计与创新团队",
    sourceType: "official",
    sourceName: "中国地质大学（武汉）研究生院",
    sourceUrl: "https://graduate.cug.edu.cn/info/1105/16145.htm",
    sourcePublishedAt: "2026-04-14",
    checkedAt: "2026-08-07",
    validity: "expired",
  },
  {
    id: "competition-guidance-notice",
    studentLevel: "both",
    category: "tutoring",
    title: "竞赛辅导内容发布说明",
    summary: "本栏目用于发布经审核的备赛经验、组队建议和校内训练资源。",
    body: "辅导内容属于经验分享时会明确标记为“学生经验”，不会使用“官方渠道”标签。当前暂无已审核学生辅导内容。",
    audience: "有参赛意向的学生",
    sourceType: "student",
    sourceName: "平台栏目说明",
    checkedAt: "2026-08-07",
  },
];

export function categoryLabel(slug: string) {
  return categories.find((category) => category.slug === slug)?.label ?? "校园信息";
}

export function daysUntil(date?: string | null) {
  if (!date) return null;
  const diff = new Date(date).getTime() - Date.now();
  return Math.ceil(diff / 86_400_000);
}
